###
POST  http://127.0.0.1:8000/auth/register
Content-Type: application/json

{"firstName": "aram", "lastName": "aine", "email": "aram@ainee.com", "phone": "+2347048581078", "password": "jeffmaine"}


###
POST https://jeffmaine.pythonanywhere.com/auth/login
Content-Type: application/json

{"email": "aram@ainee.com",  "password": "jeffmaine"}

###
GET https://jeffmaine.pythonanywhere.com/api/users/1
Content-Type: application/json

###
POST  https://jeffmaine.pythonanywhere.com/api/organisations
Content-Type: application/json

{"name": "honey", "description": "liquidd stuff"}

###
GET https://jeffmaine.pythonanywhere.com/api/organisations
Content-Type: application/json

###
GET https://jeffmaine.pythonanywhere.com/api/organisations/1
Content-Type: application/json

###
POST https://jeffmaine.pythonanywhere.com/api/organisations/2/users
Content-Type: application/json

{"userId": 1}
