###
POST  http://127.0.0.1:8000/auth/register
Content-Type: application/json

{"firstName": "ara", "lastName": "mide", "email": "aram@ide.com", "phone": "+2347048581078", "password": "jeffmaine"}


###
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{"email": "ara@mide.com",  "password": "jeffmaine"}

###
GET http://127.0.0.1:8000/api/users/1
Content-Type: application/json

###
POST  http://127.0.0.1:8000/api/organisations
Content-Type: application/json

{"name": "honey", "description": "liquidd stuff"}

###
GET http://127.0.0.1:8000/api/organisations
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/organisations/5
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/organisations/2/users
Content-Type: application/json

{"userId": 3}
